Update README.md
polybuildr/paniLog pull request #1
Opened 2016-09-14 21:38 UTC by polybuildr

2016-09-14 21:42 UTC, hharchani commented on README.md
> +
Was this newline really required?

2016-09-14 21:42 UTC, hharchani commented on README.md
> +# Contribution
Was this space really required?

2016-09-14 21:43 UTC, hharchani requested changes
Look good overall. Refer to inline comments.

2016-09-14 21:44 UTC, polybuildr commented on README.md
> +# Contribution
Yes.

2016-09-14 21:44 UTC, polybuildr commented on README.md
> +
Yes.

2016-09-14 21:44 UTC, polybuildr reviewed
LGTM.

2016-09-14 21:45 UTC, hharchani approved these changes

2016-12-29 20:14 UTC, ParthKolekar commented on README.md
> +
Yes.

2016-12-29 20:15 UTC, ParthKolekar commented on README.md
> +# Contribution
Yes.

2016-12-29 21:27 UTC, merged

2016-12-29 21:29 UTC, ParthKolekar commented
Yes.